/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mocklog4j;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Service service = new Service();
        service.action();
    }
}
